//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS_Project.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheoDoi
    {
        public int id_TheoDoi { get; set; }
        public Nullable<int> id_Truyen { get; set; }
        public Nullable<int> id_User { get; set; }
    
        public virtual Truyen Truyen { get; set; }
        public virtual User User { get; set; }
    }
}
