//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS_Project.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Truyen()
        {
            this.ChuongTruyens = new HashSet<ChuongTruyen>();
            this.TheoDois = new HashSet<TheoDoi>();
        }
    
        public int id_Truyen { get; set; }
        public Nullable<int> id_TacGia { get; set; }
        public Nullable<int> id_TheLoai { get; set; }
        public Nullable<int> id_TrangThai { get; set; }
        public string TenTruyen { get; set; }
        public string TieuDe { get; set; }
        public string AnhTruyen { get; set; }
        public string GioiThieu { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuongTruyen> ChuongTruyens { get; set; }
        public virtual TacGia TacGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheoDoi> TheoDois { get; set; }
        public virtual TrangThai TrangThai { get; set; }
    }
}
